Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: delivery-web-app-bucket-20250707
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-020cba7c55df1f615 # Ubuntu 20.04 LTS
      KeyName: delivery-keypair
      SecurityGroupIds:
        - !Ref SecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          apt update
          apt install -y openjdk-11-jdk maven mysql-server docker.io nginx
          systemctl enable mysql docker nginx
          systemctl start mysql docker nginx
          mysql -e "CREATE DATABASE delivery_db;"
          mysql -e "CREATE USER 'root'@'localhost' IDENTIFIED BY 'your_password';"
          mysql -e "GRANT ALL PRIVILEGES ON delivery_db.* TO 'root'@'localhost';"
          mysql -e "FLUSH PRIVILEGES;"
          usermod -aG docker ubuntu
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH, HTTP, HTTPS, MySQL
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: 0.0.0.0/0
Outputs:
  InstancePublicIP:
    Value: !GetAtt EC2Instance.PublicIp
  WebsiteURL:
    Value: !Sub http://${EC2Instance.PublicIp}:80